<table class="ch_basicTable">
   <tbody>
      <tr>
         <td class=""><strong>姓名</strong></td>
         <td><%=name%></td>
      </tr>
      <tr>
         <td><strong>性别</strong></td>
         <td><%=sex%></td>
      </tr>
      <tr>
         <td><strong>出身年份</strong></td>
         <td><%=bornData%></td>
      </tr>
      <tr>
         <td><strong>学历</strong></td>
         <td><%=education%></td>
      </tr>
      <tr>
         <td><strong>国籍</strong></td>
         <td><%=nationality%></td>
      </tr>
      <tr>
         <td><strong>任职日期</strong</td>
         <td><%=takeoffice%></td>
      </tr>
       <tr>
         <td><strong>离职日期</strong></td>
         <td><%=leaveoffice%></td>
      </tr>
      <tr>
         <td><strong>从业年限</strong></td>
         <td><%=workData%></td>
      </tr>
      <tr>
         <td><strong>管理基金个数</strong></td>
         <td><%=fundManagementCompany%></td>
      </tr>
   </tbody>
</table>